import Document from "../models/Document.js";

// @desc    Verify signature from QR code
// @route   GET /api/signature/verify/:documentId
export const verifySignature = async (req, res, next) => {
  try {
    const { documentId } = req.params;
    
    // Find document with signatures
    const document = await Document.findById(documentId).populate('user');
    if (!document) {
      return res.status(404).json({ message: "Document not found" });
    }
    
    if (document.status !== 'signed') {
      return res.status(400).json({ message: "Document has not been signed yet" });
    }
    
    // Return verification page HTML
    const html = `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Signature Verification - Legal Shathi</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background: #f5f5f5; }
          .container { max-width: 800px; margin: 0 auto; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
          .header { text-align: center; margin-bottom: 30px; }
          .success { color: #10b981; font-size: 24px; margin-bottom: 20px; }
          .details { background: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0; }
          .signature-info { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin: 20px 0; }
          .hash { background: #e9ecef; padding: 10px; border-radius: 4px; font-family: monospace; font-size: 12px; word-break: break-all; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1 class="success">✅ Signature Verified</h1>
            <h2>Legal Shathi - Electronic Signature Verification</h2>
          </div>
          
          <div class="details">
            <h3>📄 Document Details</h3>
            <p><strong>Title:</strong> ${document.title}</p>
            <p><strong>Status:</strong> ${document.status}</p>
            <p><strong>Signed on:</strong> ${document.signedAt ? new Date(document.signedAt).toLocaleString() : 'N/A'}</p>
          </div>
          
          <div class="signature-info">
            <div>
              <h3>📝 Latest Signature</h3>
              ${document.signatures.length > 0 ? `
                <p><strong>Signer:</strong> ${document.signatures[document.signatures.length - 1].signerName}</p>
                <p><strong>Time:</strong> ${new Date(document.signatures[document.signatures.length - 1].timestamp).toLocaleString()}</p>
                <p><strong>IP Address:</strong> ${document.signatures[document.signatures.length - 1].ipAddress}</p>
              ` : '<p>No signatures found</p>'}
            </div>
            <div>
              <h3>🔐 Cryptographic Hash</h3>
              ${document.signatures.length > 0 ? `
                <div class="hash">${document.signatures[document.signatures.length - 1].sha256Hash}</div>
              ` : '<p>No hash available</p>'}
            </div>
          </div>
          
          <div style="text-align: center; margin-top: 30px; color: #666;">
            <p>This signature has been cryptographically verified and is legally binding.</p>
            <p>Generated by Legal Shathi Electronic Signature System</p>
          </div>
        </div>
      </body>
      </html>
    `;
    
    res.setHeader('Content-Type', 'text/html');
    res.status(200).send(html);
    
  } catch (error) {
    next(error);
  }
};
