import { sendEmail } from "../utils/emailService.js";
import { logActivity } from "../utils/logActivity.js";

// @desc    Handle signature webhook
// @route   POST /api/webhooks/signature
export const handleSignatureWebhook = async (req, res, next) => {
  try {
    console.log('🔔 Webhook received:', req.body);
    
    const { event, data, timestamp } = req.body;
    
    // Log webhook activity (without userId for webhook events)
    try {
      await logActivity({
        action: 'webhook_received',
        details: {
          event,
          data,
          timestamp,
          userAgent: req.get('User-Agent'),
          ip: req.ip
        }
      });
    } catch (logError) {
      console.warn('⚠️ Activity logging failed (webhook):', logError.message);
    }
    
    // Trigger email notification based on event type
    if (event === 'signature_completed') {
      await sendSignatureWebhookEmail(data);
    } else if (event === 'document_generated') {
      await sendDocumentWebhookEmail(data);
    } else if (event === 'user_registered') {
      await sendUserWebhookEmail(data);
    }
    
    console.log('✅ Webhook processed successfully');
    res.status(200).json({ 
      message: 'Webhook processed successfully',
      event: event,
      processed_at: new Date().toISOString()
    });
    
  } catch (error) {
    console.error('❌ Webhook processing error:', error);
    res.status(500).json({ 
      message: 'Webhook processing failed',
      error: error.message 
    });
  }
};

// @desc    Handle signature callback
// @route   POST /api/callbacks/signature
export const handleSignatureCallback = async (req, res, next) => {
  try {
    console.log('🔄 Callback received:', req.body);
    
    const { status, documentId, signerName, timestamp } = req.body;
    
    // Log callback activity (without userId for callback events)
    try {
      await logActivity({
        action: 'callback_received',
        details: {
          status,
          documentId,
          signerName,
          timestamp,
          userAgent: req.get('User-Agent'),
          ip: req.ip
        }
      });
    } catch (logError) {
      console.warn('⚠️ Activity logging failed (callback):', logError.message);
    }
    
    // Send callback notification email
    await sendCallbackEmail({
      status,
      documentId,
      signerName,
      timestamp
    });
    
    console.log('✅ Callback processed successfully');
    res.status(200).json({ 
      message: 'Callback processed successfully',
      status: status,
      processed_at: new Date().toISOString()
    });
    
  } catch (error) {
    console.error('❌ Callback processing error:', error);
    res.status(500).json({ 
      message: 'Callback processing failed',
      error: error.message 
    });
  }
};

// @desc    Send webhook notification email for signature events
const sendSignatureWebhookEmail = async (data) => {
  try {
    const { documentTitle, signerName, timestamp, documentId } = data;
    
    const subject = `🔔 Webhook Alert: Document Signed - ${documentTitle}`;
    const html = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 8px;">
          <h2 style="margin: 0 0 15px 0; font-size: 24px; font-weight: bold;">🔔 Webhook Notification</h2>
          <p style="margin: 0; font-size: 16px;">Document signature event triggered</p>
        </div>
        
        <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <h3 style="margin: 0 0 15px 0; color: #333; font-size: 18px;">📋 Event Details</h3>
          <ul style="margin: 0; padding-left: 20px; color: #555;">
            <li style="margin-bottom: 8px;"><strong>Event:</strong> signature_completed</li>
            <li style="margin-bottom: 8px;"><strong>Document:</strong> ${documentTitle}</li>
            <li style="margin-bottom: 8px;"><strong>Signed by:</strong> ${signerName}</li>
            <li style="margin-bottom: 8px;"><strong>Time:</strong> ${new Date(timestamp).toLocaleString()}</li>
            <li style="margin-bottom: 8px;"><strong>Document ID:</strong> ${documentId}</li>
          </ul>
        </div>
        
        <div style="background: #e8f5e8; padding: 15px; border-radius: 8px; margin: 20px 0;">
          <p style="margin: 0; color: #2d5016; font-size: 14px;">
            <strong>✅ Success:</strong> Webhook was processed and notification sent successfully.
          </p>
        </div>
        
        <div style="text-align: center; margin-top: 30px; color: #666;">
          <p>Generated by Legal Shathi Webhook System</p>
        </div>
      </div>
    `;
    
    await sendEmail({
      to: 'newaziktider5@gmail.com',
      subject,
      html,
      text: `Webhook Alert: Document "${documentTitle}" was signed by ${signerName} at ${new Date(timestamp).toLocaleString()}`
    });
    
    console.log('📧 Signature webhook email sent successfully');
    
  } catch (error) {
    console.error('❌ Failed to send signature webhook email:', error);
  }
};

// @desc    Send webhook notification email for document events
const sendDocumentWebhookEmail = async (data) => {
  try {
    const { documentTitle, templateTitle, userEmail, timestamp } = data;
    
    const subject = `🔔 Webhook Alert: Document Generated - ${documentTitle}`;
    const html = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <div style="background: linear-gradient(135deg, #10b981 0%, #059669 100%); color: white; padding: 20px; border-radius: 8px;">
          <h2 style="margin: 0 0 15px 0; font-size: 24px; font-weight: bold;">🔔 Webhook Notification</h2>
          <p style="margin: 0; font-size: 16px;">Document generation event triggered</p>
        </div>
        
        <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <h3 style="margin: 0 0 15px 0; color: #333; font-size: 18px;">📋 Event Details</h3>
          <ul style="margin: 0; padding-left: 20px; color: #555;">
            <li style="margin-bottom: 8px;"><strong>Event:</strong> document_generated</li>
            <li style="margin-bottom: 8px;"><strong>Document:</strong> ${documentTitle}</li>
            <li style="margin-bottom: 8px;"><strong>Template:</strong> ${templateTitle}</li>
            <li style="margin-bottom: 8px;"><strong>User Email:</strong> ${userEmail}</li>
            <li style="margin-bottom: 8px;"><strong>Time:</strong> ${new Date(timestamp).toLocaleString()}</li>
          </ul>
        </div>
        
        <div style="background: #e8f5e8; padding: 15px; border-radius: 8px; margin: 20px 0;">
          <p style="margin: 0; color: #2d5016; font-size: 14px;">
            <strong>✅ Success:</strong> Webhook was processed and notification sent successfully.
          </p>
        </div>
        
        <div style="text-align: center; margin-top: 30px; color: #666;">
          <p>Generated by Legal Shathi Webhook System</p>
        </div>
      </div>
    `;
    
    await sendEmail({
      to: 'newaziktider5@gmail.com',
      subject,
      html,
      text: `Webhook Alert: Document "${documentTitle}" was generated by ${userEmail} at ${new Date(timestamp).toLocaleString()}`
    });
    
    console.log('📧 Document webhook email sent successfully');
    
  } catch (error) {
    console.error('❌ Failed to send document webhook email:', error);
  }
};

// @desc    Send webhook notification email for user events
const sendUserWebhookEmail = async (data) => {
  try {
    const { userName, userEmail, timestamp, action } = data;
    
    const subject = `🔔 Webhook Alert: User Activity - ${action}`;
    const html = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <div style="background: linear-gradient(135deg, #f59e0b 0%, #d97706 100%); color: white; padding: 20px; border-radius: 8px;">
          <h2 style="margin: 0 0 15px 0; font-size: 24px; font-weight: bold;">🔔 Webhook Notification</h2>
          <p style="margin: 0; font-size: 16px;">User activity event triggered</p>
        </div>
        
        <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <h3 style="margin: 0 0 15px 0; color: #333; font-size: 18px;">📋 Event Details</h3>
          <ul style="margin: 0; padding-left: 20px; color: #555;">
            <li style="margin-bottom: 8px;"><strong>Event:</strong> ${action}</li>
            <li style="margin-bottom: 8px;"><strong>User:</strong> ${userName}</li>
            <li style="margin-bottom: 8px;"><strong>Email:</strong> ${userEmail}</li>
            <li style="margin-bottom: 8px;"><strong>Time:</strong> ${new Date(timestamp).toLocaleString()}</li>
          </ul>
        </div>
        
        <div style="background: #e8f5e8; padding: 15px; border-radius: 8px; margin: 20px 0;">
          <p style="margin: 0; color: #2d5016; font-size: 14px;">
            <strong>✅ Success:</strong> Webhook was processed and notification sent successfully.
          </p>
        </div>
        
        <div style="text-align: center; margin-top: 30px; color: #666;">
          <p>Generated by Legal Shathi Webhook System</p>
        </div>
      </div>
    `;
    
    await sendEmail({
      to: 'newaziktider5@gmail.com',
      subject,
      html,
      text: `Webhook Alert: User "${userName}" performed action "${action}" at ${new Date(timestamp).toLocaleString()}`
    });
    
    console.log('📧 User webhook email sent successfully');
    
  } catch (error) {
    console.error('❌ Failed to send user webhook email:', error);
  }
};

// @desc    Send callback notification email
const sendCallbackEmail = async ({ status, documentId, signerName, timestamp }) => {
  try {
    const subject = `🔄 Callback Alert: Signature Status - ${status}`;
    const html = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <div style="background: linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%); color: white; padding: 20px; border-radius: 8px;">
          <h2 style="margin: 0 0 15px 0; font-size: 24px; font-weight: bold;">🔄 Callback Notification</h2>
          <p style="margin: 0; font-size: 16px;">Signature status callback received</p>
        </div>
        
        <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <h3 style="margin: 0 0 15px 0; color: #333; font-size: 18px;">📋 Callback Details</h3>
          <ul style="margin: 0; padding-left: 20px; color: #555;">
            <li style="margin-bottom: 8px;"><strong>Status:</strong> ${status}</li>
            <li style="margin-bottom: 8px;"><strong>Document ID:</strong> ${documentId}</li>
            <li style="margin-bottom: 8px;"><strong>Signer:</strong> ${signerName}</li>
            <li style="margin-bottom: 8px;"><strong>Time:</strong> ${new Date(timestamp).toLocaleString()}</li>
          </ul>
        </div>
        
        <div style="background: #e8f5e8; padding: 15px; border-radius: 8px; margin: 20px 0;">
          <p style="margin: 0; color: #2d5016; font-size: 14px;">
            <strong>✅ Success:</strong> Callback was processed and notification sent successfully.
          </p>
        </div>
        
        <div style="text-align: center; margin-top: 30px; color: #666;">
          <p>Generated by Legal Shathi Callback System</p>
        </div>
      </div>
    `;
    
    await sendEmail({
      to: 'newaziktider5@gmail.com',
      subject,
      html,
      text: `Callback Alert: Signature status "${status}" for document ${documentId} by ${signerName} at ${new Date(timestamp).toLocaleString()}`
    });
    
    console.log('📧 Callback email sent successfully');
    
  } catch (error) {
    console.error('❌ Failed to send callback email:', error);
  }
};
